syntax = "proto3";
option go_package = "github.com/GiorgosMarga/distributed_cache/api/cachepb";
package types;



service CacheService {
    rpc Get(GetRequest) returns (GetResponse);
    rpc TransferKeys(TransferRequest) returns (TransferResponse);
    rpc GetAll(GetAllRequest) returns (GetAllResponse);
    rpc Set(SetRequest) returns (SetResponse);
    rpc Delete(DeleteRequest) returns (DeleteResponse);
    rpc Join(JoinRequest) returns (JoinResponse);
    rpc Leave(LeaveRequest) returns (LeaveResponse);
    rpc IsAlive(AliveRequest) returns (AliveResponse);
}
message TransferRequest {
  repeated Item items = 1;
}
message TransferResponse {
  bool success = 1;
  int32 nkeys = 2;
}

message GetRequest {
  bytes key = 1;
}
message GetResponse {
  bytes value = 1;
  bool hit  = 2;
}

message Item {
  bytes key = 1;
  bytes value = 2;
  uint32 ttl = 3;
  int64 insertedAt = 4;
}

message GetAllRequest {
}
message GetAllResponse {
  repeated Item items = 1;
}


message SetRequest {
  Item item = 1;
}


message SetResponse {
  bool success = 1;
}

message DeleteRequest {
  bytes key = 1;
}


message DeleteResponse {
  bool success = 1;
}

message JoinRequest {
  string node_address = 1;
  string target_address = 2;
}


message JoinResponse {
  repeated string peer_addresses = 1;
}

message LeaveRequest {
  string node_address = 1;
}

message LeaveResponse {
  bool success = 1;
}

message AliveRequest {
  string node_address = 1;
}

message AliveResponse {
  bool success = 1;
}